// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZi-dd1di3aWISUJvFbw5d_LSUT2gUOs',
    appId: '1:612357526404:web:1e2595addc53c0641543d1',
    messagingSenderId: '612357526404',
    projectId: 'qwandery-6feb2',
    authDomain: 'qwandery-6feb2.firebaseapp.com',
    storageBucket: 'qwandery-6feb2.firebasestorage.app',
    measurementId: 'G-B7T6RX4RME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDO4AE46SmmoyT22THTXzSrhYbZaNj8E4',
    appId: '1:612357526404:android:460b6816985fe4871543d1',
    messagingSenderId: '612357526404',
    projectId: 'qwandery-6feb2',
    storageBucket: 'qwandery-6feb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_JLph0mPoSYN8yYeZ7yXMSmPp3oTeS0',
    appId: '1:612357526404:ios:8a2c53e952334fdc1543d1',
    messagingSenderId: '612357526404',
    projectId: 'qwandery-6feb2',
    storageBucket: 'qwandery-6feb2.firebasestorage.app',
    iosBundleId: 'com.example.iwAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_JLph0mPoSYN8yYeZ7yXMSmPp3oTeS0',
    appId: '1:612357526404:ios:8a2c53e952334fdc1543d1',
    messagingSenderId: '612357526404',
    projectId: 'qwandery-6feb2',
    storageBucket: 'qwandery-6feb2.firebasestorage.app',
    iosBundleId: 'com.example.iwAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbZi-dd1di3aWISUJvFbw5d_LSUT2gUOs',
    appId: '1:612357526404:web:4f9cb963757362ce1543d1',
    messagingSenderId: '612357526404',
    projectId: 'qwandery-6feb2',
    authDomain: 'qwandery-6feb2.firebaseapp.com',
    storageBucket: 'qwandery-6feb2.firebasestorage.app',
    measurementId: 'G-J3QVWP1CFK',
  );
}
